# Generated by Django 5.2.7 on 2025-12-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologist_app', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
