# Generated by Django 5.2.7 on 2025-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologist_app', '0003_alter_productvariant_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='catalog_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
